name: Build the Docker Image

on:
  push:
    branches:
      - master
      - build-with-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Install Jekyll
      run: sudo apt-get install ruby-full build-essential zlib1g-dev && sudo gem install jekyll bundler
    - name: Build the Jekyll Site
      run: jekyll build
    - name: Package the Docker Image
      run: docker build --tag="kamon/kamon.io:$GITHUB_SHA" $GITHUB_WORKSPACE