name: Build the Docker Image

on:
  push:
    branches:
      - master
      - build-with-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: docker run --rm --volume="$GITHUB_WORKSPACE/kamon.io:/srv/jekyll" jekyll/jekyll:3.8 jekyll build